# Imagen liviana con Java 17
FROM eclipse-temurin:17-jre
WORKDIR /app

# Copiamos el jar generado por Maven
COPY target/*.jar app.jar

# Puerto interno del microservicio usuario
EXPOSE 8081

# Spring Boot toma SERVER_PORT como server.port
ENV SERVER_PORT=8081

# Arranca la aplicación
ENTRYPOINT ["java", "-jar", "app.jar"]
